openapi: 3.1.0
info:
  title: Document PDF API
  description: API for uploading and retrieving PDFs associated with documents.
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local Development Server

paths:
  /upload_pdf/{document_id}:
    post:
      summary: Upload a PDF file for a document
      operationId: uploadPdf
      parameters:
        - name: document_id
          in: path
          required: true
          description: The ID of the document to which the PDF will be associated.
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The PDF file to upload.
      responses:
        '200':
          description: PDF uploaded successfully
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Error uploading the PDF

  /pdf/{document_id}:
    get:
      summary: Retrieve the PDF file for a document
      operationId: getPdf
      parameters:
        - name: document_id
          in: path
          required: true
          description: The ID of the document to retrieve the PDF for.
          schema:
            type: string
      responses:
        '200':
          description: PDF file retrieved successfully
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: PDF file not found
